// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYTE3-ksbD7Xe2dg_5cYbi0PAej6BQDU',
    appId: '1:696648593173:web:f2256fe543fdd02c6e431c',
    messagingSenderId: '696648593173',
    projectId: 'comp1786expensetracker',
    authDomain: 'comp1786expensetracker.firebaseapp.com',
    databaseURL: 'https://comp1786expensetracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'comp1786expensetracker.firebasestorage.app',
    measurementId: 'G-DGQMJFSSYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wxa7h6nF_M_Ybxtw9iwKn06Yf5X-HH4',
    appId: '1:696648593173:android:78401429d9bce0f36e431c',
    messagingSenderId: '696648593173',
    projectId: 'comp1786expensetracker',
    databaseURL: 'https://comp1786expensetracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'comp1786expensetracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPkuNDbXYRYSdQpuuwefHy17TSQqMeSvY',
    appId: '1:696648593173:ios:548f53b1b57199e96e431c',
    messagingSenderId: '696648593173',
    projectId: 'comp1786expensetracker',
    databaseURL: 'https://comp1786expensetracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'comp1786expensetracker.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPkuNDbXYRYSdQpuuwefHy17TSQqMeSvY',
    appId: '1:696648593173:ios:548f53b1b57199e96e431c',
    messagingSenderId: '696648593173',
    projectId: 'comp1786expensetracker',
    databaseURL: 'https://comp1786expensetracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'comp1786expensetracker.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyYTE3-ksbD7Xe2dg_5cYbi0PAej6BQDU',
    appId: '1:696648593173:web:1ee3a421743c59a76e431c',
    messagingSenderId: '696648593173',
    projectId: 'comp1786expensetracker',
    authDomain: 'comp1786expensetracker.firebaseapp.com',
    databaseURL: 'https://comp1786expensetracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'comp1786expensetracker.firebasestorage.app',
    measurementId: 'G-FH04G7RVFY',
  );
}
